server:
  port: 8640

spring:
  application:
    name: microservice-gateway-zuul
#    user:
#      name: admin
#      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka.yimiao.tk:8761/eureka/
  instance:
    status-page-url-path: /actuator/health # 更改 eureka info 页面为 actuator health 页面

zuul:
  routes:
    microservice-mall-front: /front/** #配置指定的微服务服务路径
    microservice-mall-manager: /manager/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  retryable: true

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#
#logging:
#  level:
#    com.netflix: DEBUG #设置netflix包的日志为debug

management:
  endpoints:
    web:
      exposure:
        include: '*'


