%YAML 1.2
---
# 默认配置
spring:
  profiles:
    active: dev
  application:
    name: microservice-mall-front
    #  security:
    #    user:
    #      name: admin
    #      password: admin
    # spring 数据连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://qq.yimiaohome.top:3306/xmall?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      password: xmall
      username: xmall
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000 #超时等待
      time-between-eviction-runs-millis: 60000 #空闲连接检测间隔
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters:
        commons-log.connection-logger-name: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,防止sql注入
      filter:
        stat:
          log-slow-sql: true
      stat-view-servlet:
        login-username: root
        login-password: root

swagger:
  enabled: true

mybatis:
  mapper-locations: classpath:tk.yimiao.yimiaocloud.microservice.mall.base.pojo/*.xml

# session 过期时间
session:
  expire: 1800

---
spring:
  profiles: dev
  redis:
    host: redis.yimiaohome.top
    port: 6379
    # http://localhost:7777/druid/sql.html  访问这个页面

server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: /swagger-ui.html # 更改 eureka info 页面为 swagger 页面
    prefer-ip-address: true
    instance-id: 127.0.0.1:8761

---
spring:
  profiles: release
  redis:
    host: redis.yimiaohome.top
    port: 6379
    # http://localhost:7777/druid/sql.html  访问这个页面

server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: http://eureka.yimiaohome.top:8761/eureka/
  instance:
    status-page-url-path: /swagger-ui.html # 更改 eureka info 页面为 swagger 页面
    prefer-ip-address: true
    instance-id: ${HOST_NAME}:${PORT}
    ip-address: ${HOST_NAME}